import React from 'react'
import { Link } from 'react-router-dom';

import { FaQuestionCircle } from "react-icons/fa";

const FAQ = () => {
  return (
    <div className='py-8 px-4 mb-4 max-w-6xl mx-auto'>
      <div className="text-3xl mb-4 px-4 flex items-center gap-2">
        <FaQuestionCircle className='text-info' />
        <h4 className="font-extrabold">FAQs</h4>
      </div>
      <div className="flex flex-col gap-2">
        <div className="collapse collapse-arrow bg-base-200">
          <input type="radio" name="my-accordion-2" defaultChecked />
          <div className="collapse-title text-xl font-medium">What is Link-In-Bio?</div>
          <div className="collapse-content">
            <p>Link-In-Bio is a free link shortening service that allows you to shorten long URLs into shorter, more manageable links.</p>
          </div>
        </div>
        <div className="collapse collapse-arrow bg-base-200">
          <input type="radio" name="my-accordion-2" />
          <div className="collapse-title text-xl font-medium">How do I use Link-In-Bio?</div>
          <div className="collapse-content">
            <p>Simply enter the URL you want to shorten in the input field, click the "Shorten" button, and we'll generate a shorter link for you. Also you can check the <Link to='/guid' className='link link-success link-hover'>How To Use</Link> section.</p>
          </div>
        </div>
        <div className="collapse collapse-arrow bg-base-200">
          <input type="radio" name="my-accordion-2" />
          <div className="collapse-title text-xl font-medium">How long do the shortened links last?</div>
          <div className="collapse-content">
            <p>The shortened links generated by Link-In-Bio are permanent and will not expire.</p>
          </div>
        </div>
        <div className="collapse collapse-arrow bg-base-200">
          <input type="radio" name="my-accordion-2" />
          <div className="collapse-title text-xl font-medium">Is my shortened link secure?</div>
          <div className="collapse-content">
            <p>Yes, our link shortening service uses industry-standard security measures to ensure that your shortened links are safe and secure.</p>
          </div>
        </div>
        <div className="collapse collapse-arrow bg-base-200">
          <input type="radio" name="my-accordion-2" />
          <div className="collapse-title text-xl font-medium">Can I customize my shortened link?</div>
          <div className="collapse-content">
            <p>Currently, we don't offer customization options for shortened links. We are working on adding this feature in the future. However you can enable/disable your links in your panel.</p>
          </div>
        </div>
        <div className="collapse collapse-arrow bg-base-200">
          <input type="radio" name="my-accordion-2" />
          <div className="collapse-title text-xl font-medium">How long does it take to shorten a link?</div>
          <div className="collapse-content">
            <p>Our link shortening service is instant. As soon as you enter a URL and click the "Shorten" button, we'll generate a shortened link for you.</p>
          </div>
        </div>
        <div className="collapse collapse-arrow bg-base-200">
          <input type="radio" name="my-accordion-2" />
          <div className="collapse-title text-xl font-medium">Can I use Link-In-Bio for personal or non-commercial use?</div>
          <div className="collapse-content">
            <p>Yes, Link-In-Bio is free to use for both personal and non-commercial purposes.</p>
          </div>
        </div>
        <div className="collapse collapse-arrow bg-base-200">
          <input type="radio" name="my-accordion-2" />
          <div className="collapse-title text-xl font-medium">Do you have a limit on the number of links I can shorten?</div>
          <div className="collapse-content">
            <p>No, there is no limit on the number of links you can shorten using Link-In-Bio. You can shorten as many links as you need, for free!</p>
          </div>
        </div>
      </div>
    </div>
  )
}

export default FAQ